Starting program: /usr/bin/python3 GUI3.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3ad0700 (LWP 31588)]
[New Thread 0x7ffff12cf700 (LWP 31589)]
[New Thread 0x7fffeeace700 (LWP 31590)]
[New Thread 0x7fffd3da2700 (LWP 31591)]
[New Thread 0x7fffd2042700 (LWP 31592)]
[New Thread 0x7fffd1841700 (LWP 31593)]
[New Thread 0x7fffd1040700 (LWP 31594)]
[New Thread 0x7fffbb95a700 (LWP 31595)]
[Thread 0x7fffbb95a700 (LWP 31595) exited]
[New Thread 0x7fffbb95a700 (LWP 31622)]
[New Thread 0x7fffbab72700 (LWP 31623)]
[Thread 0x7fffd3da2700 (LWP 31591) exited]
[Thread 0x7fffd2042700 (LWP 31592) exited]
[Thread 0x7fffd1040700 (LWP 31594) exited]
[Thread 0x7fffd1841700 (LWP 31593) exited]
[Thread 0x7fffeeace700 (LWP 31590) exited]
[Thread 0x7ffff12cf700 (LWP 31589) exited]
[Thread 0x7ffff3ad0700 (LWP 31588) exited]
[Thread 0x7fffbb95a700 (LWP 31622) exited]
[Thread 0x7ffff7fcf700 (LWP 31584) exited]
[Inferior 1 (process 31584) exited normally]
Starting program: /usr/bin/python3 GUI3.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3ad0700 (LWP 31625)]
[New Thread 0x7ffff12cf700 (LWP 31626)]
[New Thread 0x7ffff0ace700 (LWP 31627)]
[New Thread 0x7fffd3da2700 (LWP 31628)]
[New Thread 0x7fffd2042700 (LWP 31629)]
[New Thread 0x7fffd1841700 (LWP 31630)]
[New Thread 0x7fffd1040700 (LWP 31631)]
[New Thread 0x7fffbb95a700 (LWP 31637)]
[New Thread 0x7fffbab72700 (LWP 31669)]
[New Thread 0x7fffba371700 (LWP 31670)]
[Thread 0x7fffbb95a700 (LWP 31637) exited]
[Thread 0x7fffd2042700 (LWP 31629) exited]
[Thread 0x7fffd3da2700 (LWP 31628) exited]
[Thread 0x7fffd1841700 (LWP 31630) exited]
[Thread 0x7fffd1040700 (LWP 31631) exited]
[Thread 0x7ffff0ace700 (LWP 31627) exited]
[Thread 0x7ffff12cf700 (LWP 31626) exited]
[Thread 0x7ffff3ad0700 (LWP 31625) exited]
[Thread 0x7fffbab72700 (LWP 31669) exited]
[Thread 0x7ffff7fcf700 (LWP 31624) exited]
[Inferior 1 (process 31624) exited normally]
Starting program: /usr/bin/python3 GUI3.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3ad0700 (LWP 31672)]
[New Thread 0x7ffff32cf700 (LWP 31673)]
[New Thread 0x7fffeeace700 (LWP 31674)]
[New Thread 0x7fffd3da2700 (LWP 31675)]
[New Thread 0x7fffd2042700 (LWP 31676)]
[New Thread 0x7fffd1841700 (LWP 31677)]
[New Thread 0x7fffd1040700 (LWP 31678)]
[New Thread 0x7fffbb95a700 (LWP 31679)]
[Thread 0x7fffbb95a700 (LWP 31679) exited]
[New Thread 0x7fffbb95a700 (LWP 31680)]
[New Thread 0x7fffbab72700 (LWP 31681)]
[Thread 0x7fffd2042700 (LWP 31676) exited]
[Thread 0x7fffd3da2700 (LWP 31675) exited]
[Thread 0x7fffd1841700 (LWP 31677) exited]
[Thread 0x7fffd1040700 (LWP 31678) exited]
[Thread 0x7fffeeace700 (LWP 31674) exited]
[Thread 0x7ffff32cf700 (LWP 31673) exited]
[Thread 0x7ffff3ad0700 (LWP 31672) exited]
[Thread 0x7fffbb95a700 (LWP 31680) exited]
[Thread 0x7ffff7fcf700 (LWP 31671) exited]
[Inferior 1 (process 31671) exited normally]
Starting program: /usr/bin/python3 GUI3.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3ad0700 (LWP 31683)]
[New Thread 0x7ffff32cf700 (LWP 31684)]
[New Thread 0x7fffeeace700 (LWP 31685)]
[New Thread 0x7fffd3da2700 (LWP 31686)]
[New Thread 0x7fffd2042700 (LWP 31687)]
[New Thread 0x7fffd1841700 (LWP 31688)]
[New Thread 0x7fffd1040700 (LWP 31689)]
[New Thread 0x7fffbb95a700 (LWP 31690)]
[Thread 0x7fffbb95a700 (LWP 31690) exited]
[New Thread 0x7fffbb95a700 (LWP 31694)]
[New Thread 0x7fffbab72700 (LWP 31695)]
[Thread 0x7fffd2042700 (LWP 31687) exited]
[Thread 0x7fffd3da2700 (LWP 31686) exited]
[Thread 0x7fffd1841700 (LWP 31688) exited]
[Thread 0x7fffd1040700 (LWP 31689) exited]
[Thread 0x7fffeeace700 (LWP 31685) exited]
[Thread 0x7ffff32cf700 (LWP 31684) exited]
[Thread 0x7ffff3ad0700 (LWP 31683) exited]
[Thread 0x7fffbb95a700 (LWP 31694) exited]
[Thread 0x7ffff7fcf700 (LWP 31682) exited]
[Inferior 1 (process 31682) exited normally]
Starting program: /usr/bin/python3 GUI3.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3ad0700 (LWP 31697)]
[New Thread 0x7ffff32cf700 (LWP 31698)]
[New Thread 0x7fffeeace700 (LWP 31699)]
[New Thread 0x7fffd3da2700 (LWP 31700)]
[New Thread 0x7fffd2042700 (LWP 31701)]
[New Thread 0x7fffd1841700 (LWP 31702)]
[New Thread 0x7fffd1040700 (LWP 31703)]
[New Thread 0x7fffbb95a700 (LWP 31704)]

Thread 9 "python3" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffbb95a700 (LWP 31704)]
0x00007ffff7825428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  0x00007ffff7825428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff782702a in __GI_abort () at abort.c:89
#2  0x00007ffff78677ea in __libc_message (do_abort=do_abort@entry=2, 
    fmt=fmt@entry=0x7ffff7980ed8 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff787037a in malloc_printerr (ar_ptr=<optimised out>, ptr=<optimised out>, 
    str=0x7ffff7980fa0 "double free or corruption (fasttop)", action=3) at malloc.c:5006
#4  _int_free (av=<optimised out>, p=<optimised out>, have_lock=1) at malloc.c:3867
#5  0x00007ffff7873350 in _int_realloc (av=av@entry=0x7fffb4000020, 
    oldp=oldp@entry=0x7fffb40148e0, oldsize=oldsize@entry=48, nb=nb@entry=64) at malloc.c:4358
#6  0x00007ffff7874839 in __GI___libc_realloc (oldmem=0x7fffb40148f0, bytes=48) at malloc.c:3045
#7  0x00007fffe0ff72ee in QVector<QWidget*>::realloc (this=this@entry=0x1ecdce0, asize=2, 
    aalloc=4) at ../../include/QtCore/../../src/corelib/tools/qvector.h:509
#8  0x00007fffe0ff73bd in QVector<QWidget*>::append (this=this@entry=0x1ecdce0, 
    t=@0x7fffbb959290: 0x1be1060) at ../../include/QtCore/../../src/corelib/tools/qvector.h:577
#9  0x00007fffe0ff55e0 in QWidgetBackingStore::addDirtyWidget (rgn=..., widget=0x1be1060, 
    this=0x1ecdcc0) at painting/qbackingstore_p.h:157
#10 QWidgetBackingStore::markDirty (this=0x1ecdcc0, rect=..., widget=widget@entry=0x1be1060, 
    updateImmediately=updateImmediately@entry=false, 
    invalidateBuffer=invalidateBuffer@entry=false) at painting/qbackingstore.cpp:718
#11 0x00007fffe0e1427e in QWidget::update (this=this@entry=0x1be1060, rect=...)
    at kernel/qwidget.cpp:10599
#12 0x00007fffe0e14333 in QWidget::update (this=this@entry=0x1be1060) at kernel/qwidget.cpp:10560
#13 0x00007fffe11f558e in QLCDNumberPrivate::internalSetString (this=this@entry=0x1be7120, s=...)
    at widgets/qlcdnumber.cpp:851
#14 0x00007fffe11f64b3 in QLCDNumber::display (this=0x1be1060, num=<optimised out>)
    at widgets/qlcdnumber.cpp:667
#15 0x00007fffe1cc04c4 in ?? ()
   from /usr/lib/python3/dist-packages/PyQt4/QtGui.cpython-35m-x86_64-linux-gnu.so
#16 0x00000000004e9b7f in PyCFunction_Call ()
#17 0x00000000005372f4 in PyEval_EvalFrameEx ()
#18 0x000000000053b7e4 in PyEval_EvalFrameEx ()
#19 0x0000000000540f9b in PyEval_EvalCodeEx ()
#20 0x00000000004ebe37 in ?? ()
#21 0x00000000005c1797 in PyObject_Call ()
#22 0x000000000053920b in PyEval_EvalFrameEx ()
#23 0x000000000053b7e4 in PyEval_EvalFrameEx ()
#24 0x000000000053b7e4 in PyEval_EvalFrameEx ()
#25 0x0000000000540f9b in PyEval_EvalCodeEx ()
#26 0x00000000004ebd23 in ?? ()
#27 0x00000000005c1797 in PyObject_Call ()
#28 0x00000000004fb9ce in ?? ()
#29 0x00000000005c1797 in PyObject_Call ()
#30 0x0000000000534d90 in PyEval_CallObjectWithKeywords ()
#31 0x0000000000609c02 in ?? ()
#32 0x00007ffff7bc16ba in start_thread (arg=0x7fffbb95a700) at pthread_create.c:333
#33 0x00007ffff78f741d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
quit
